# -*- encoding: utf-8 -*-
=begin
=実績設定

=end

#==============================================================================
# ■ NWConst::Library
#==============================================================================
module NWConst::Library  
  # メダル獲得時の効果音
  SE_GAIN_MEDAL = RPG::SE.new("Powerup", 90, 140)
  
  # メダル獲得時の効果音ID
  NO_USE_MEDAL = [
  ]
  
  MEDAL_DATA = {
    # 例
#   メダルID => { ※メダルIDは1~9999に収めてください
#      :icon_id => アイコンID,
#      :title => "タイトル",
#      :description => "解説",
#      :priority => :,
#    },
    1 => {
      :icon_id => 193,
      :title => "The Rescue of Hans",
      :description => "You saved the kidnapped villager.",
      :priority => 1,
    },
    2 => {
      :icon_id => 193,
      :title => "Descent of Goddess Ilias",
      :description => "You have been recognized as an unblessed hero.",
      :priority => 2,
    },
    3 => {
      :icon_id => 191,
      :title => "The Monster Lord's Slave",
      :description => "The Monster Lord Alice was added to your party... or perhaps you were added to hers.",
      :priority => 3,
    },
    4 => {
      :icon_id => 191,
      :title => "The Goddess's Slave",
      :description => "The Goddess Ilias was added to your party... or perhaps you were added to hers.",
      :priority => 4,
    },
    5 => {
      :icon_id => 193,
      :title => "Childhood Tag-along",
      :description => "Sonya forced her way into the party...",
      :priority => 5,
    },
    6 => {
      :icon_id => 193,
      :title => "A Proof of Bravery",
      :description => "You've been recognized by a guard for the discovery of the Proof of Bravery.",
      :priority => 6,
    },
    7 => {
      :icon_id => 193,
      :title => "Merchant Rescue",
      :description => "You brought the lost merchant to safety.",
      :priority => 7,
    },
    8 => {
      :icon_id => 193,
      :title => "Bandit Dissolution",
      :description => "You broke up the monster bandits' group and rehabilitated the girls.",
      :priority => 8,
    },
    9 => {
      :icon_id => 193,
      :title => "Resolved Phoenix Tail Trade",
      :description => "You liberated the deceived Phoenix Girl.",
      :priority => 9,
    },
    10 => {
      :icon_id => 192,
      :title => "Traveler From A Parallel World",
      :description => "You continue your adventure in a parallel world.",
      :priority => 10,
    },
    11 => {
      :icon_id => 193,
      :title => "Harpies' Savior",
      :description => "You cured the harpies of an epidemic.",
      :priority => 11,
    },
    12 => {
      :icon_id => 193,
      :title => "Mysterious Medal Queen",
      :description => "You received your first audience with the Medal Queen.",
      :priority => 12,
    },
    13 => {
      :icon_id => 193,
      :title => "Slug Extermination",
      :description => "You triumphed over the slug boss in Slug Tower.",
      :priority => 13,
    },
    15 => {
      :icon_id => 192,
      :title => "Chasing Your Father",
      :description => "One day, you will catch up to him.",
      :priority => 15,
    },
    16 => {
      :icon_id => 193,
      :title => "Micaela's Disappearance",
      :description => "Where did she go...?",
      :priority => 16,
    },
    17 => {
      :icon_id => 192,
      :title => "Welcome to Sentora",
      :description => "Your first visit to the continent of Sentora.",
      :priority => 17,
    },
    18 => {
      :icon_id => 193,
      :title => "Collapse of a Shota-harem",
      :description => "You defeated the brainwashed Meia.",
      :priority => 18,
    },
    19 => {
      :icon_id => 193,
      :title => "Chasing the Four Spirits",
      :description => "You seek the strength to walk a righteous path from history.",
      :priority => 19,
    },
    20 => {
      :icon_id => 192,
      :title => "As a Hero...",
      :description => "The last wish of Micaela, engraved upon your heart.",
      :priority => 20,
    },
    21 => {
      :icon_id => 193,
      :title => "Mechanized Pope No. 7",
      :description => "You discovered the secret of the church...",
      :priority => 21,
    },
    22 => {
      :icon_id => 193,
      :title => "Closing Up the Zombie Business",
      :description => "You put an end to the disturbance at the haunted mansion and delivered punishment to Chrome.",
      :priority => 22,
    },
    23 => {
      :icon_id => 192,
      :title => "The Spirit of the Wind",
      :description => "You acquired the power of Sylph.",
      :priority => 23,
    },
    24 => {
      :icon_id => 193,
      :title => "A Soul of Burning Justice",
      :description => "You got dragged into the duties of a so-called Hero of Justice.",
      :priority => 24,
    },
    25 => {
      :icon_id => 193,
      :title => "Black Alice Strikes Back",
      :description => "The devilish tea party never ends.",
      :priority => 25,
    },
    26 => {
      :icon_id => 193,
      :title => "Tomboy Princess's Honor Restored",
      :description => "You secretly saved Sabasa.",
      :priority => 26,
    },
    27 => {
      :icon_id => 193,
      :title => "The Idol's Curtain Call",
      :description => "Saki-chan, Sparkle!☆",
      :priority => 27,
    },
    28 => {
      :icon_id => 193,
      :title => "The Witch's Dinner",
      :description => "You have settled the troubles in Witch Hunt Village.",
      :priority => 28,
    },
    29 => {
      :icon_id => 192,
      :title => "The Spirit of the Earth",
      :description => "You acquired the power of Gnome.",
      :priority => 29,
    },
    30 => {
      :icon_id => 191,
      :title => "Wish from a Ruined World",
      :description => "You engraved the hopes of La Croix upon your heart.",
      :priority => 30,
    },
    31 => {
      :icon_id => 193,
      :title => "Fishy Pirate Debut",
      :description => "Your work as a member of the Fishy Pirates has begun.",
      :priority => 31,
    },
    32 => {
      :icon_id => 193,
      :title => "Navy's Pride",
      :description => "Your work as a member of the Navy has begun.",
      :priority => 32,
    },
    33 => {
      :icon_id => 193,
      :title => "Queen's Cup Champion",
      :description => "You made your name known as the victor of the Queen's Cup.",
      :priority => 33,
    },
    34 => {
      :icon_id => 193,
      :title => "Sukiyaki Dusk",
      :description => "Solved the case of the Minotauros disappearances.",
      :priority => 34,
    },
    35 => {
      :icon_id => 193,
      :title => "Shrine Pilgrimage",
      :description => "You settled the turmoil in Yamatai Village.",
      :priority => 35,
    },
    36 => {
      :icon_id => 193,
      :title => "Her Judgement",
      :description => "You exposed the truth of the Magical Advisor Mephisto.",
      :priority => 36,
    },
    37 => {
      :icon_id => 192,
      :title => "For Whom the Bell Tolls",
      :description => "This wonderful world is worth fighting for.",
      :priority => 37,
    },
    38 => {
      :icon_id => 193,
      :title => "For Whom the Bell Tolls",
      :description => "This wonderful world is worth fighting for.",
      :priority => 39,
    },
    39 => {
      :icon_id => 193,
      :title => "Bugs and Flowers and Birds and Cats",
      :description => "Subdued the civil war in Plansect Village.",
      :priority => 38,
    },
    40 => {
      :icon_id => 192,
      :title => "Spirit of Water",
      :description => "You acquired the power of Undine.",
      :priority => 40,
    },
    41 => {
      :icon_id => 193,
      :title => "Mission Start",
      :description => "After meeting with a reassuring helper, the time has come to begin the operation.",
      :priority => 41,
    },
    42 => {
      :icon_id => 193,
      :title => "Gold Fort Breakthrough",
      :description => "The operation has only just begun.",
      :priority => 42,
    },
    43 => {
      :icon_id => 193,
      :title => "March Hills Breakthrough",
      :description => "Grangold Castle is finally before your very eyes.",
      :priority => 43,
    },
    44 => {
      :icon_id => 192,
      :title => "Victory Feast",
      :description => "You liberated Grangold, ending the Great War.",
      :priority => 44,
    },
    45 => {
      :icon_id => 193,
      :title => "Queen of the Flies",
      :description => "You ousted the Beelzebubs from the Ghost Ship.",
      :priority => 45,
    },
    46 => {
      :icon_id => 193,
      :title => "From the Northern Sea",
      :description => "You proved your strength to Poseidoness and received the Silver Orb.",
      :priority => 46,
    },
    47 => {
      :icon_id => 193,
      :title => "Succubi's Wild Feast",
      :description => "You resolved the conflict in Succubus Village.",
      :priority => 47,
    },
    48 => {
      :icon_id => 193,
      :title => "Young Unison",
      :description => "You restored Emily and Cassandra to their original forms.",
      :priority => 48,
    },
    49 => {
      :icon_id => 193,
      :title => "Magical Girl Gran☆Beria",
      :description => "You'll pretend you never saw that.",
      :priority => 49,
    },
    50 => {
      :icon_id => 192,
      :title => "Spirit of Fire",
      :description => "You acquired the power of Salamander.",
      :priority => 50,
    },
    51 => {
      :icon_id => 193,
      :title => "A Legend In the Flesh",
      :description => "You met the legendary hero Heinrich from 500 years ago.",
      :priority => 51,
    },
    52 => {
      :icon_id => 193,
      :title => "Salvation of the Four Kingdoms",
      :description => "You defeated the vanguards of the Monster Lord's armies besieging the four kingdoms.",
      :priority => 52,
    },
    53 => {
      :icon_id => 193,
      :title => "Elf and Fairy Afternoon",
      :description => "You defeated the Queen Elf.",
      :priority => 53,
    },
    54 => {
      :icon_id => 193,
      :title => "The Name of the Rose",
      :description => "You snapped the Queen Alraune back to sanity.",
      :priority => 54,
    },
    55 => {
      :icon_id => 193,
      :title => "Reconciliation with the Mermaids",
      :description => "You defeated the Queen Mermaid.",
      :priority => 55,
    },
    56 => {
      :icon_id => 193,
      :title => "Spider's Sunset",
      :description => "You defeated the Spider Princess.",
      :priority => 56,
    },
    57 => {
      :icon_id => 193,
      :title => "One Hundred Years of Solitude",
      :description => "You defeated the Queen Vampire.",
      :priority => 57,
    },
    58 => {
      :icon_id => 193,
      :title => "Start With Correspondence",
      :description => "You received the Red Orb from the Elf Princess.",
      :priority => 58,
    },
    59 => {
      :icon_id => 193,
      :title => "Beyond Time",
      :description => "You obtained the Blue Orb from the Monster Lord's Castle from 500 years ago.",
      :priority => 59,
    },
    60 => {
      :icon_id => 193,
      :title => "To the Snow Continent",
      :description => "You embark on the mysterious continent at long last.",
      :priority => 60,
    },
    61 => {
      :icon_id => 193,
      :title => "The Third Seraph",
      :description => "You obtained Eden's help at the Snow Shrine.",
      :priority => 61,
    },
    62 => {
      :icon_id => 193,
      :title => "Itty-Bitty Squishy Angels",
      :description => "You revived the two Seraphs.",
      :priority => 62,
    },
    63 => {
      :icon_id => 191,
      :title => "The Drifting Relations of the Sword and the Darkness",
      :description => "The hero's father and the Monster Lord's mother meet; what will befall the son and daughter afterwards?",
      :priority => 63,
    },
    64 => {
      :icon_id => 191,
      :title => "Don't Leave Me",
      :description => "No one knew the girl who fought and saved the world.",
      :priority => 64,
    },
    65 => {
      :icon_id => 191,
      :title => "Hope Inherited",
      :description => "With the hope of a destroyed world in their hearts, the Seekers go to the Battle of Wisdom.",
      :priority => 65,
    },
    66 => {
      :icon_id => 191,
      :title => "Sonya's Bizarre Adventure",
      :description => "Sonya seems to have survived a long adventure.",
      :priority => 66,
    },
    67 => {
      :icon_id => 193,
      :title => "Pest Relief",
      :description => "You were able to save the cockroaches.",
      :priority => 67,
    },
    68 => {
      :icon_id => 193,
      :title => "Pest Extermination",
      :description => "You were unable to save the cockroaches...",
      :priority => 68,
    },
    69 => {
      :icon_id => 193,
      :title => "Reiwa Era: End of the Tanuki War",
      :description => "You prevented a war by reconciling the Tanuki and the Kitsune clans.",
      :priority => 69,
    },
    70 => {
      :icon_id => 193,
      :title => "Hikikomori Rebellion, Suppressed",
      :description => "The turmoil in the Elf Village was safely contained.",
      :priority => 70,
    },
    71 => {
      :icon_id => 192,
      :title => "The Great Decision",
      :description => "At last, you will make a great decision--",
      :priority => 71,
    },
    72 => {
      :icon_id => 191,
      :title => "As a Comrade of the Dark Goddess",
      :description => "You have chosen to fight alongside Alice.",
      :priority => 72,
    },
    73 => {
      :icon_id => 191,
      :title => "As an Apostle of the Goddess Ilias",
      :description => "You have chosen to fight alongside Ilias.",
      :priority => 73,
    },
    74 => {
      :icon_id => 193,
      :title => "Alma Elma's Homecoming",
      :description => "Looks like she can go on your journey without any worries now.",
      :priority => 74,
    },
    75 => {
      :icon_id => 193,
      :title => "The Legendary Blacksmith",
      :description => "You've finally found the legendary blacksmith.",
      :priority => 75,
    },
    76 => {
      :icon_id => 193,
      :title => "Angelic Dominion Arrival!",
      :description => "You've finally set foot in the enemy's territory, the Angelic Dominion.",
      :priority => 76,
    },
    77 => {
      :icon_id => 193,
      :title => "First Angelic Dominion Transfer",
      :description => "You used a device in the Administrator's tower to warp to another continent.",
      :priority => 77,
    },
    78 => {
      :icon_id => 193,
      :title => "Angelic Dominion's Water Spirit",
      :description => "You acquired the power of Grandine.",
      :priority => 78,
    },
    79 => {
      :icon_id => 193,
      :title => "Angelic Dominion's Earth Spirit",
      :description => "You acquired the power of Gnomaren.",
      :priority => 79,
    },
    80 => {
      :icon_id => 193,
      :title => "Contact with the Underground Organization",
      :description => "You've enlisted the aid of the rebel organization Reverse Kreuz.",
      :priority => 80,
    },
    81 => {
      :icon_id => 192,
      :title => "Angelic Dominion Sabasa Liberation",
      :description => "You've defeated Gabriela and liberated Sabasa from the angels' rule.",
      :priority => 81,
    },
    82 => {
      :icon_id => 193,
      :title => "She ate chaos!",
      :description => "Nuruko displayed an unexpected ability at Angelic Dominion Finoa.",
      :priority => 82,
    },
    83 => {
      :icon_id => 192,
      :title => "Angelic Dominion Colosseum Championship",
      :description => "You won the combat tournament at Angelic Dominion Grand Noah.",
      :priority => 83,
    },
    84 => {
      :icon_id => 193,
      :title => "Luka Imprisoned",
      :description => "You were apprehended by Sariela at Angelic Dominion Grangold.",
      :priority => 84,
    },
    85 => {
      :icon_id => 192,
      :title => "The Great Escape!",
      :description => "You escaped from the Great Prison of Grangold with the help of your friends.",
      :priority => 85,
    },
    86 => {
      :icon_id => 193,
      :title => "Assassin from the Moon",
      :description => "You were attacked by people from the moon at Angelic Dominion Grangold.",
      :priority => 86,
    },
    87 => {
      :icon_id => 193,
      :title => "Angelic Dominion's Fire Spirit",
      :description => "You acquired the power of Gigamander.",
      :priority => 87,
    },
    88 => {
      :icon_id => 193,
      :title => "The Lost Hero",
      :description => "You sealed Heinrich's Soul at the Sealed Sinner's Prison.",
      :priority => 88,
    },
    89 => {
      :icon_id => 192,
      :title => "Return of the Monster Lord",
      :description => "The Monster Lord makes her long-awaited return to the ruins of her castle.",
      :priority => 89,
    },
    90 => {
      :icon_id => 192,
      :title => "Fall of the Remina Research Institute",
      :description => "You destroyed the Remina Research Institute and eradicated its detestable studies. ",
      :priority => 90,
    },
    91 => {
      :icon_id => 192,
      :title => "Monster Lord's Castle Reclaimed!",
      :description => "You reclaimed the Monster Lord's Castle in the Singularity World from the forces of the Angelic Dominion.",
      :priority => 91,
    },
    93 => {
      :icon_id => 193,
      :title => "Reconciliation with the Replicants",
      :description => "You've formed a bond with the Replicants of Luddite Village.",
      :priority => 93,
    },
    94 => {
      :icon_id => 193,
      :title => "Angelic Dominion's Wind Spirit",
      :description => "You acquired the power of Zylphe.",
      :priority => 94,
    },
    95 => {
      :icon_id => 193,
      :title => "ラファエラとの思わぬ共闘",
      :description => "混沌に取り込まれそうになったコスモスを倒した",
      :priority => 95,
    },
    96 => {
      :icon_id => 192,
      :title => "Attack, Black Alice Army!",
      :description => "You escaped from Angelic Dominion San Ilia while the Black Alice Army was attacking.",
      :priority => 96,
    },
    97 => {
      :icon_id => 193,
      :title => "Mysterious Siblings' Farewell",
      :description => "You repelled the Black Alice Army's invasion of Angelic Dominion Grand Noah.",
      :priority => 97,
    },
    98 => {
      :icon_id => 193,
      :title => "Wrath of the Lilith Sisters",
      :description => "You repelled the Black Alice Army's invasion of Angelic Dominion Sabasa.",
      :priority => 98,
    },
    99 => {
      :icon_id => 192,
      :title => "Restoring the Hero",
      :description => "You freed Heinrich's Soul from the Sealed Sinner's Prison.",
      :priority => 99,
    },
    100 => {
      :icon_id => 191,
      :title => "Curtain Call and Farewell to Dad",
      :description => "You drove back Black Alice and inherited your father's soul.",
      :priority => 100,
    },
    101 => {
      :icon_id => 193,
      :title => "One Small Step for Man...",
      :description => "魔導船で月面へと降り立った",
      :priority => 101,
    },
    102 => {
      :icon_id => 192,
      :title => "母の助け・大陸突入編",
      :description => "You've enlisted the aid of Lucifina on the moon.",
      :priority => 102,
    },
    103 => {
      :icon_id => 193,
      :title => "It's time for the decisive battle!",
      :description => "You flew to the Ilias Continent from Mt. Saint Amos.",
      :priority => 103,
    },
    104 => {
      :icon_id => 193,
      :title => "Mithra Sealed Castle, Liberated",
      :description => "You acquired the armaments that were sealed in Mithra Castle.",
      :priority => 105,
    },
    105 => {
      :icon_id => 193,
      :title => "Randolph's Comeback",
      :description => "The legendary blacksmith Randolph, who had been despondent, has finally found new inspiration.",
      :priority => 106,
    },
    106 => {
      :icon_id => 192,
      :title => "Storming the Ilias Temple!",
      :description => "You have finally entered the Ilias Temple.",
      :priority => 107,
    },
    107 => {
      :icon_id => 191,
      :title => "Destroyer of the Angelic Dominion",
      :description => "You have cleared the Angelic Dominion Route.",
      :priority => 108,
    },
    108 => {
      :icon_id => 193,
      :title => "Monster Realm Arrival!",
      :description => "You've finally set foot in the enemy's territory, the Monster Realm.",
      :priority => 201,
    },
    109 => {
      :icon_id => 193,
      :title => "Succubus Village Overthrow",
      :description => "You ousted Queen Eva and seized power over Succubus Village.",
      :priority => 202,
    },
    110 => {
      :icon_id => 193,
      :title => "Pure Lazarus",
      :description => "You've enlisted the aid of the rebel organization Ilias Kreuz.",
      :priority => 202,
    },
    111 => {
      :icon_id => 192,
      :title => "The City of Green's Fall",
      :description => "You defeated Kanon and seized Monster Realm Grangold.",
      :priority => 203,
    },
    112 => {
      :icon_id => 192,
      :title => "The City of Water's Fall",
      :description => "You defeated Kanade and seized Monster Realm Grand Noah.",
      :priority => 204,
    },
    113 => {
      :icon_id => 193,
      :title => "Monster Realm's Fire Spirit",
      :description => "You acquired the power of Grimoire.",
      :priority => 205,
    },
    114 => {
      :icon_id => 193,
      :title => "Monster Realm's Water Spirit",
      :description => "You acquired the power of Ghatanothoa.",
      :priority => 206,
    },
    115 => {
      :icon_id => 193,
      :title => "Harmony of Snake and Tentacle",
      :description => "Peace between the lamias and scyllas of Plansect Village has been achieved.",
      :priority => 207,
    },
    116 => {
      :icon_id => 193,
      :title => "Operation Capture Yamatai, Start!",
      :description => "You joined forces with the Monster Realm's Eden and set out to conquer Yamatai.",
      :priority => 208,
    },
    117 => {
      :icon_id => 192,
      :title => "Mechanical City Conquest",
      :description => "You drove Monster Realm Yamatai into a crisis and managed to escape.",
      :priority => 209,
    },
    118 => {
      :icon_id => 193,
      :title => "ﾄﾘと和解せよ",
      :description => "You ended the strife amongst the harpies of Finoa.",
      :priority => 210,
    },
    119 => {
      :icon_id => 193,
      :title => "A New Age of Pirates",
      :description => "You defeated the infamous Roza Pirates of the Monster Realm.",
      :priority => 211,
    },
    120 => {
      :icon_id => 193,
      :title => "Monster Realm's Wind Spirit",
      :description => "You acquired the power of Ambrosia.",
      :priority => 212,
    },
    121 => {
      :icon_id => 192,
      :title => "Puppet Circus Invasion!",
      :description => "You escaped from Monster Realm San Ilia while the Puppet Circus was attacking.",
      :priority => 213,
    },
    122 => {
      :icon_id => 193,
      :title => "Puppet Show in the Green City",
      :description => "You repelled the Puppet Circus' invasion of Monster Realm Grangold.",
      :priority => 214,
    },
    123 => {
      :icon_id => 193,
      :title => "Fighting Alongside Father",
      :description => "You repelled the Puppet Circus' invasion of Monster Realm Grand Noah.",
      :priority => 215,
    },
    124 => {
      :icon_id => 193,
      :title => "機械の村の人形草子",
      :description => "You repelled the Puppet Circus' invasion of Monster Realm Yamatai.",
      :priority => 216,
    },
    125 => {
      :icon_id => 192,
      :title => "姉との別れ",
      :description => "You defeated Kagetsumugi and dismantled the Puppet Circus.",
      :priority => 217,
    },
    126 => {
      :icon_id => 193,
      :title => "Burn! SabasaMan!",
      :description => "You defeated Queen Eva and got SabasaMan to join your party.",
      :priority => 218,
    },
    127 => {
      :icon_id => 193,
      :title => "Monster Realm's Earth Spirit",
      :description => "You acquired the power of Loa.",
      :priority => 219,
    },
    128 => {
      :icon_id => 192,
      :title => "Calamity Star Demiurge Activate!",
      :description => "The enemy's superweapon is finally on the move.",
      :priority => 220,
    },
    129 => {
      :icon_id => 193,
      :title => "迫撃！　トリプル・エデン",
      :description => "You repelled Hiruko's invasion of the hidden village of Enrika.",
      :priority => 221,
    },
    130 => {
      :icon_id => 193,
      :title => "This is the End",
      :description => "You defeated Kagetsumugi and Black Alice at the Black Mansion.",
      :priority => 222,
    },
    131 => {
      :icon_id => 193,
      :title => "Sonya Does Not Exist",
      :description => "You couldn't get Sonya back from the Place of Memory.",
      :priority => 223,
    },
    132 => {
      :icon_id => 193,
      :title => "母の助け・妖星攻略編",
      :description => "You've enlisted the aid of Lucifina on the moon.",
      :priority => 224,
    },
    133 => {
      :icon_id => 193,
      :title => "The Calamity Star's Destruction",
      :description => "You defeated Hiruko and destroyed the Calamity Star Demiurge.",
      :priority => 225,
    },
    134 => {
      :icon_id => 193,
      :title => "封牢の解放",
      :description => "魔界の封牢に閉じ込められていた者達を解き放った",
      :priority => 226,
    },
    135 => {
      :icon_id => 192,
      :title => "Storming the Dark Goddess' Castle!",
      :description => "You have finally entered the Dark Goddess' Castle.",
      :priority => 227,
    },
    136 => {
      :icon_id => 191,
      :title => "Judgement of the Monster Realm",
      :description => "You have cleared the Monster Realm Route.",
      :priority => 228,
    },
    137 => {
      :icon_id => 191,
      :title => "Observer of Chaos",
      :description => "You inherited the power of the White Rabbit, along with the memories of parallel worlds.",
      :priority => 229,
    },
    138 => {
      :icon_id => 193,
      :title => "See You Next Go-Round",
      :description => "You have said your farewell to the White Rabbit... for this go-around.",
      :priority => 104,
    },
    139 => {
      :icon_id => 191,
      :title => "The Third Way",
      :description => "Your companions from the Angelic Dominion and Monster Realm routes have finally come together.",
      :priority => 301,
    },
    140 => {
      :icon_id => 193,
      :title => "世界を救う同志として",
      :description => "智の同盟と接触し協力を得た",
      :priority => 302,
    },
    141 => {
      :icon_id => 192,
      :title => "祝福されざるもの",
      :description => "混沌の神を造り出す事に成功した",
      :priority => 303,
    },
    142 => {
      :icon_id => 193,
      :title => "一家集合！",
      :description => "両親と共に戦う時がやって来た",
      :priority => 304,
    },
    143 => {
      :icon_id => 193,
      :title => "生まれ変わった世界へ",
      :description => "深き混沌から脱出し、合一世界に降り立った",
      :priority => 305,
    },
    144 => {
      :icon_id => 193,
      :title => "折れない剣",
      :description => "ミカエラが堕天し、混沌の力を得た",
      :priority => 306,
    },
    145 => {
      :icon_id => 193,
      :title => "混沌の父の片鱗",
      :description => "混沌の力で、アンゴルモアを一時退却させた",
      :priority => 307,
    },
    146 => {
      :icon_id => 191,
      :title => "仲間を求めて",
      :description => "イリアスヴィルから新たなる旅立ちを迎えた",
      :priority => 308,
    },
    147 => {
      :icon_id => 193,
      :title => "混沌の鍛冶場オープン",
      :description => "伝説の鍛冶屋達を混沌の鍛冶場に集めよう",
      :priority => 309,
    },
    148 => {
      :icon_id => 193,
      :title => "緑からの解放",
      :description => "ガブリエラと華音を撃退し、グランゴルドを平定した",
      :priority => 310,
    },
    149 => {
      :icon_id => 193,
      :title => "粘妖の守護者",
      :description => "禍撫軍を撃退し、グランドノアを守り抜いた",
      :priority => 311,
    },
    150 => {
      :icon_id => 193,
      :title => "女王の帰還",
      :description => "行方不明になっていた女王を魔導学園で発見した",
      :priority => 312,
    },
    151 => {
      :icon_id => 193,
      :title => "肉に埋もれた城",
      :description => "蛭蟲の手からサバサを奪還した",
      :priority => 313,
    },
    152 => {
      :icon_id => 193,
      :title => "アジドル",
      :description => "アジ・ダハーカをステージから引きずり下ろした",
      :priority => 314,
    },
    153 => {
      :icon_id => 193,
      :title => "聖都灰燼",
      :description => "サン・イリアが崩壊し、結果的に騒乱の種は消えた",
      :priority => 315,
    },
    154 => {
      :icon_id => 193,
      :title => "暴走ウェポン撃退",
      :description => "ヤマタイの地で荒れ狂うマガツオオミカミを撃退した",
      :priority => 316,
    },
    155 => {
      :icon_id => 192,
      :title => "月面要塞攻略",
      :description => "月面基地でシンギュラリティを撃破した",
      :priority => 317,
    },
    156 => {
      :icon_id => 193,
      :title => "ハーピーの春",
      :description => "ハーピーの集落を守り、騒動の種を取り除いた",
      :priority => 318,
    },
    157 => {
      :icon_id => 193,
      :title => "おかえり天使たち",
      :description => "ミカエラちゃんとルシフィナちゃんが復帰した",
      :priority => 319,
    },
    158 => {
      :icon_id => 193,
      :title => "風と舞い踊る",
      :description => "風の精霊三体が戻ってきた",
      :priority => 320,
    },
    159 => {
      :icon_id => 193,
      :title => "無口でおしゃべりな土",
      :description => "土の精霊三体が戻ってきた",
      :priority => 321,
    },
    160 => {
      :icon_id => 193,
      :title => "静かな水と荒ぶる水",
      :description => "水の精霊三体が戻ってきた",
      :priority => 322,
    },
    161 => {
      :icon_id => 193,
      :title => "回り巡る炎",
      :description => "炎の精霊三体が戻ってきた",
      :priority => 323,
    },
    162 => {
      :icon_id => 192,
      :title => "僕の頭はゆうえんち",
      :description => "十二体の精霊が集結した",
      :priority => 324,
    },
    163 => {
      :icon_id => 193,
      :title => "女神復活の祈り",
      :description => "イリアス神殿で女神復活のための儀式を開始した",
      :priority => 325,
    },
    164 => {
      :icon_id => 193,
      :title => "復活した邪神！？",
      :description => "邪神城で少女アリスフィーズと合流した",
      :priority => 326,
    },
    165 => {
      :icon_id => 193,
      :title => "我等が主のために",
      :description => "封魔の洞窟で邪神復活のための儀式を開始した",
      :priority => 327,
    },
    166 => {
      :icon_id => 193,
      :title => "初心を忘れるな",
      :description => "パピが正気を取り戻した",
      :priority => 328,
    },
    167 => {
      :icon_id => 192,
      :title => "これは悲恋の物語",
      :description => "海軍や海賊と協力しワールドドロウンを撃破した",
      :priority => 329,
    },
    168 => {
      :icon_id => 192,
      :title => "胡蝶の夢",
      :description => "混沌の力を手にしたコスモスを撃破した",
      :priority => 330,
    },
    169 => {
      :icon_id => 192,
      :title => "魔芸師の罪は魔芸師が",
      :description => "ラ・クロワの助けを借りノーライフキングを撃破した",
      :priority => 331,
    },
    170 => {
      :icon_id => 192,
      :title => "大帝瞬断",
      :description => "コロシアムでアンゴルモアに打ち勝った",
      :priority => 332,
    },
    171 => {
      :icon_id => 192,
      :title => "ヤマタイの地に安寧を",
      :description => "オロチの洞に潜むマガツオオミカミを滅ぼした",
      :priority => 333,
    },
    172 => {
      :icon_id => 193,
      :title => "妖星陥落",
      :description => "妖星デミウルゴスにて蛭蟲・禍撫・華音を撃破した",
      :priority => 334,
    },
    173 => {
      :icon_id => 192,
      :title => "お前らはモリを出ろ",
      :description => "植物族の力を借りバアル・ゼブブを撃退した",
      :priority => 335,
    },
    174 => {
      :icon_id => 193,
      :title => "四人組の再更生",
      :description => "ヴァニラ達四人を「強欲」の力から解き放った",
      :priority => 336,
    },
    175 => {
      :icon_id => 193,
      :title => "怠惰の克服",
      :description => "ルミを「怠惰」の力から解き放った",
      :priority => 337,
    },
    176 => {
      :icon_id => 193,
      :title => "嫉妬の連鎖",
      :description => "リリィを「嫉妬」の力から解き放った",
      :priority => 338,
    },
    177 => {
      :icon_id => 193,
      :title => "アンガーマネジメント",
      :description => "牛魔王を「憤怒」の力から解き放った",
      :priority => 339,
    },
    178 => {
      :icon_id => 193,
      :title => "満ち足りた食欲",
      :description => "カサンドラを「暴食」の力から解き放った",
      :priority => 340,
    },
    179 => {
      :icon_id => 193,
      :title => "溢れ出る色欲",
      :description => "ウィッチサキュバスを「色欲」の力から解き放った",
      :priority => 341,
    },
    180 => {
      :icon_id => 193,
      :title => "高慢と偏見とヴァンパイア",
      :description => "クィーンヴァンパイアを「傲慢」の力から解き放った",
      :priority => 342,
    },
    181 => {
      :icon_id => 192,
      :title => "罪と罰",
      :description => "大罪の殿堂で七つの大罪を撃破した",
      :priority => 343,
    },
    182 => {
      :icon_id => 193,
      :title => "巡り廻る人形遣いの因果",
      :description => "影紬の新しいボディを完成させた",
      :priority => 344,
    },
    183 => {
      :icon_id => 192,
      :title => "全てを識らざる者",
      :description => "光の塔と闇の塔で全てを識る者を撃破した",
      :priority => 345,
    },
    184 => {
      :icon_id => 192,
      :title => "たのしい女体のたび",
      :description => "リリスの体内に潜り込んだエキドナクィーンを撃破した",
      :priority => 347,
    },
    185 => {
      :icon_id => 192,
      :title => "クトゥルフの呼び声",
      :description => "ルルイエで名状しがたきものを撃退した",
      :priority => 348,
    },
    186 => {
      :icon_id => 192,
      :title => "侵蝕された侵蝕者",
      :description => "侵蝕された妖星で次元侵蝕者を滅ぼした",
      :priority => 349,
    },
    187 => {
      :icon_id => 192,
      :title => "不滅を滅ぼすもの",
      :description => "ゴルド火山でダークフェニックスを撃破した",
      :priority => 350,
    },
    188 => {
      :icon_id => 192,
      :title => "銀河魔神の逆襲",
      :description => "迫り来る星喰いを月面基地で撃破した",
      :priority => 351,
    },
    189 => {
      :icon_id => 193,
      :title => "混沌に満ちた塔で",
      :description => "管理者の塔でヌルコを助け出した",
      :priority => 352,
    },
    190 => {
      :icon_id => 193,
      :title => "究極のトリニティ",
      :description => "三人のエデンが合一し究極形態となった",
      :priority => 357,
    },
    191 => {
      :icon_id => 193,
      :title => "全てを受け入れた勇者",
      :description => "ハインリヒが己自身を受け入れ、真の勇者となった",
      :priority => 358,
    },
    192 => {
      :icon_id => 192,
      :title => "千年の孤独",
      :description => "黒の屋敷にて黒のアリスを撃破した",
      :priority => 359,
    },
    193 => {
      :icon_id => 191,
      :title => "おかえり、ソニア",
      :description => "ソニアが仲間に復帰した",
      :priority => 360,
    },
    194 => {
      :icon_id => 193,
      :title => "ちょっと怖い姉",
      :description => "アドラメレクを仲間にした",
      :priority => 361,
    },
    195 => {
      :icon_id => 193,
      :title => "導く者と死の管理者",
      :description => "白兎と死神を仲間にした",
      :priority => 362,
    },
    196 => {
      :icon_id => 192,
      :title => "さらば最強の戦士",
      :description => "蓬莱山で虚竜を撃破した",
      :priority => 363,
    },
    197 => {
      :icon_id => 192,
      :title => "邪神を継ぎし者",
      :description => "アリスが邪神の力を受け継いだ",
      :priority => 364,
    },
    198 => {
      :icon_id => 192,
      :title => "創世の女神ついに降臨",
      :description => "イリアスが真の力を取り戻した",
      :priority => 365,
    },
    199 => {
      :icon_id => 193,
      :title => "正史の息子たち",
      :description => "ネロとネリスを仲間にした",
      :priority => 366,
    },
    200 => {
      :icon_id => 192,
      :title => "ジハードバスター",
      :description => "三闘神を全員撃破した",
      :priority => 367,
    },
    201 => {
      :icon_id => 191,
      :title => "破滅に打ち勝つ者",
      :description => "十六の破滅事象を全て討ち倒した",
      :priority => 368,
    },
    202 => {
      :icon_id => 191,
      :title => "さよなら、混沌の父娘",
      :description => "混沌の父娘は長い旅へと出かけた",
      :priority => 369,
    },
    203 => {
      :icon_id => 4755,
      :title => "混沌を晴らす者",
      :description => "混沌が晴れ世界が平和になった",
      :priority => 370,
    },
    204 => {
      :icon_id => 193,
      :title => "魔法少女ぐらん☆べりあ",
      :description => "グランベリアは悪夢に打ち勝ち魔法少女となった",
      :priority => 346,
    },
    205 => {
      :icon_id => 193,
      :title => "怪盗騒ぎ、終幕",
      :description => "三つの指輪を手に入れ、二人の大怪盗が仲間になった",
      :priority => 355,
    },
    206 => {
      :icon_id => 193,
      :title => "復興への第一歩",
      :description => "イリアス神殿に人が集まり、復興が始まった",
      :priority => 353,
    },
    207 => {
      :icon_id => 193,
      :title => "スサノオの末裔",
      :description => "狐華の出自が明らかになり、仲間になった",
      :priority => 354,
    },
    208 => {
      :icon_id => 193,
      :title => "倫理は浜で死にました",
      :description => "ナタリア大陸北岸への魔物漂着事件は内輪の仕業だった",
      :priority => 356,
    },
    209 => {
      :icon_id => 193,
      :title => "コンプライアンス僧侶",
      :description => "確かに肌の露出はほとんどない",
      :priority => 371,
    },
    210 => {
      :icon_id => 193,
      :title => "職無キ者",
      :description => "それでもやはり無職は無職",
      :priority => 372,
    },

#==============================================================================
    # 買い物金額
    1001 => {
      :icon_id => 193,
      :title => "First Time Shopper",
      :description => "You bought your first item at a shop.",
      :priority => 1001,    
    },
    1002 => {
      :icon_id => 193,
      :title => "Regular Shopper",
      :description => "You bought 30,000G worth of goods; you really like your shops.",
      :priority => 1002,    
    },
    1003 => {
      :icon_id => 192,
      :title => "Shopping King",
      :description => "You bought 300,000G worth of goods; you're contributing to the regional economy.",
      :priority => 1003,    
    },
    1004 => {
      :icon_id => 191,
      :title => "Shopping Addict",
      :description => "You bought 3,000,000G worth of goods; you can't stop shopping.",
      :priority => 1004,    
    },
    1005 => {
      :icon_id => 191,
      :title => "Shopping Master",
      :description => "You bought 3,000,000G worth of goods; you are a master of shopping.",
      :priority => 1005,    
    },
    # 鍛冶利用数
    1011 => {
      :icon_id => 193,
      :title => "Your First Synthesis",
      :description => "You commissioned your first synthesis to a blacksmith.",
      :priority => 1011,    
    },
    1012 => {
      :icon_id => 193,
      :title => "Blacksmith Binger",
      :description => "You commissioned 50 blacksmith syntheses; kind of a habit now.",
      :priority => 1012,    
    },
    1013 => {
      :icon_id => 192,
      :title => "Blacksmith Maniac",
      :description => "You commissioned 200 blacksmith syntheses; what else can you make?",
      :priority => 1013,    
    },
    1014 => {
      :icon_id => 191,
      :title => "Blacksmith King",
      :description => "You commissioned 500 blacksmith syntheses; you're now the king,",
      :priority => 1014,    
    },
    1015 => {
      :icon_id => 191,
      :title => "Blacksmith God",
      :description => "You commissioned 1,000 blacksmith syntheses; you're revered as a god.",
      :priority => 1015,    
    },
    # 転職回数
    1021 => {
      :icon_id => 193,
      :title => "Your First Job Change",
      :description => "You made your first job change in Ilias Temple.",
      :priority => 1021,    
    },
    1022 => {
      :icon_id => 193,
      :title => "Job Hopper",
      :description => "You changed jobs 10 times; you've learned what several jobs are like.",
      :priority => 1022,    
    },
    1023 => {
      :icon_id => 192,
      :title => "Job Collector",
      :description => "You changed jobs 100 times; you've become a regular visitor at the Ilias Temple.",
      :priority => 1023,    
    },
    1024 => {
      :icon_id => 191,
      :title => "Job Connoisseur",
      :description => "You changed jobs 500 times; you've made a name for yourself in the employment industry.",
      :priority => 1024,    
    },
    1025 => {
      :icon_id => 191,
      :title => "Infinite Recruit",
      :description => "You changed jobs 1,000 times; you've even destroyed the very concept of a job.",
      :priority => 1025,    
    },
    # 転種回数
    1031 => {
      :icon_id => 193,
      :title => "Your First Race Change",
      :description => "You changed races for the first time in Ilias Temple.",
      :priority => 1031,    
    },
    1032 => {
      :icon_id => 193,
      :title => "Habitual Race Changer",
      :description => "You changed races 5 times; you're starting to understand different species.",
      :priority => 1032,    
    },
    1033 => {
      :icon_id => 192,
      :title => "Shapeshifter",
      :description => "You changed races 50 times; it's becoming unclear what species you are.",
      :priority => 1033,    
    },
    1034 => {
      :icon_id => 191,
      :title => "Race Change Moratorium",
      :description => "You changed races 300 times; have you found your true self?",
      :priority => 1034,    
    },
    1035 => {
      :icon_id => 191,
      :title => "Race Changing God",
      :description => "You changed races 500 times; you have reached the god's throne.",
      :priority => 1035,    
    },
    # 戦闘回数
    1041 => {
      :icon_id => 193,
      :title => "Your First Battle!",
      :description => "You fought an opponent for the first time, an unforgettable event.",
      :priority => 1041,    
    },
    1042 => {
      :icon_id => 193,
      :title => "Seasoned Adventurer",
      :description => "You've made it through 300 battles; you're quite the adventurer.",
      :priority => 1042,    
    },
    1043 => {
      :icon_id => 192,
      :title => "Polished Hero",
      :description => "After 2,000 battles, you are a hero with no equal.",
      :priority => 1043,    
    },
    1044 => {
      :icon_id => 191,
      :title => "World Savior",
      :description => "After 5,000 battles, you should be able to save the world now.",
      :priority => 1044,    
    },
    1045 => {
      :icon_id => 191,
      :title => "Ultimate Fighter",
      :description => "After 10,000 battles, you have become the ultimate fighter.",
      :priority => 1045,    
    },
    # 逃亡回数
    1051 => {
      :icon_id => 193,
      :title => "Your First Escape",
      :description => "You will never forget the humiliation of running away from an enemy for the first time.",
      :priority => 1051,    
    },
    1052 => {
      :icon_id => 193,
      :title => "Run For Freedom",
      :description => "You've escaped 10 times; running away just feels natural at this point.",
      :priority => 1052,    
    },
    1053 => {
      :icon_id => 192,
      :title => "Life On The Run",
      :description => "You ran away 50 times; now you're just running away from life.",
      :priority => 1053,    
    },
    1054 => {
      :icon_id => 191,
      :title => "Escape To Win Another Day",
      :description => "You ran away 150 times; you no longer feel like you're winning.",
      :priority => 1054,    
    },
    1055 => {
      :icon_id => 191,
      :title => "Escape is a Battlefield",
      :description => "You ran away 300 times; escaping is a battle in of itself!",
      :priority => 1055,    
    },
    # 敗北回数
    1061 => {
      :icon_id => 193,
      :title => "Your First Defeat",
      :description => "You have been defeated by your opponent, receiving your rewar- No, your disgrace.",
      :priority => 1061,    
    },
    1062 => {
      :icon_id => 193,
      :title => "Adventure Bait",
      :description => "You have been defeated 30 times; that many just makes you prey.",
      :priority => 1062,    
    },
    1063 => {
      :icon_id => 192,
      :title => "Dried Fish",
      :description => "You have been defeated 100 times; you've given nourishment to many monsters.",
      :priority => 1063,    
    },
    1064 => {
      :icon_id => 191,
      :title => "Defeatist Hero",
      :description => "You have been defeated 500 times; you have embraced total defeat.",
      :priority => 1064,    
    },
    1065 => {
      :icon_id => 191,
      :title => "Lose And Be Raped",
      :description => "You have been defeated 1,000 times; the title has been restored.",
      :priority => 1065,    
    },
    # 総撃破数
    1071 => {
      :icon_id => 193,
      :title => "Monster Killer",
      :description => "You've turned the tables on 500 monsters.",
      :priority => 1071,    
    },
    1072 => {
      :icon_id => 192,
      :title => "Monster Buster",
      :description => "You've eliminated 5,000 monsters.",
      :priority => 1072,    
    },
    1073 => {
      :icon_id => 191,
      :title => "Monster Crusher",
      :description => "You've crushed 10,000 monsters.",
      :priority => 1073,    
    },
    1074 => {
      :icon_id => 191,
      :title => "Monster Annihilator",
      :description => "You've annihilated 50,000 monsters.",
      :priority => 1074,    
    },
    # 職業公開率
    1201 => {
      :icon_id => 191,
      :title => "Jobs Mastered: 100%",
      :description => "You've mastered every job.",
      :priority => 1201,    
    },
    # 種族公開率
    1202 => {
      :icon_id => 191,
      :title => "Races Mastered: 100%",
      :description => "You've mastered every race.",
      :priority => 1202,    
    },
    # キャラ図鑑コンプ率
    1301 => {
      :icon_id => 191,
      :title => "Character Book: 100%",
      :description => "You've filled out all entries in the character book.",
      :priority => 1301,    
    },
    # 魔物図鑑コンプ率
    1311 => {
      :icon_id => 191,
      :title => "Monster Book: 100%",
      :description => "You've filled out all entries in the monster book.",
      :priority => 1311,    
    },
    # 武器図鑑コンプ率
    1321 => {
      :icon_id => 191,
      :title => "Weapon Book: 100%",
      :description => "You've filled out all entries in the weapon book.",
      :priority => 1321,    
    },
    # 防具図鑑コンプ率
    1331 => {
      :icon_id => 191,
      :title => "Armor Book: 100%",
      :description => "You've filled out all entries in the armor book.",
      :priority => 1331,    
    },
    # アクセサリ図鑑コンプ率
    1341 => {
      :icon_id => 191,
      :title => "Accessory Book: 100%",
      :description => "You've filled out all entries in the accessory book.",
      :priority => 1341,    
    },
    # アイテム図鑑コンプ率
    1351 => {
      :icon_id => 191,
      :title => "Item Book: 100%",
      :description => "You've filled out all entries in the item book.",
      :priority => 1351,    
    },
    # 全体収集率
    1371 => {
      :icon_id => 191,
      :title => "All Collections 100% Complete",
      :description => "You've acheived 100% Library Completion Rate.",
      :priority => 1371,    
    },
#==============================================================================
    1401 => {
      :icon_id => 193,
      :title => "Medal Beginner",
      :description => "You've started your small medal collection.",
      :priority => 1401,    
    },
    1402 => {
      :icon_id => 193,
      :title => "Medal Collector",
      :description => "You learned the name of the Medal Queen.",
      :priority => 1402,    
    },
    1403 => {
      :icon_id => 192,
      :title => "Medal Mania",
      :description => "You've become captivated by medal trading.",
      :priority => 1403,    
    },
    1404 => {
      :icon_id => 191,
      :title => "Medal Master",
      :description => "小さなメダルをひたすらに交換し続けた",
      :priority => 1404,    
    },
    1406 => {
      :icon_id => 193,
      :title => "Large Medal Beginner",
      :description => "You've started your large medal collection.",
      :priority => 1406,    
    },
    1407 => {
      :icon_id => 193,
      :title => "Large Medal Collector",
      :description => "You've been frequently visiting the Medal King.",
      :priority => 1407,    
    },
    1408 => {
      :icon_id => 192,
      :title => "Large Medal Mania",
      :description => "You've become captivated by large medal trading.",
      :priority => 1408,    
    },
    1409 => {
      :icon_id => 192,
      :title => "Large Medal Master",
      :description => "大きなメダルをひたすらに交換し続けた",
      :priority => 1409,    
    },
    1411 => {
      :icon_id => 193,
      :title => "First BF victory",
      :description => "You got your first victory in a Battle Fuck.",
      :priority => 1411,    
    },
    1412 => {
      :icon_id => 193,
      :title => "Accomplished Battle Fucker",
      :description => "You defeated 15 Battle Fuckers.",
      :priority => 1412,    
    },
    1413 => {
      :icon_id => 192,
      :title => "Veteran Battle Fucker",
      :description => "You defeated 30 Battle Fuckers.",
      :priority => 1413,    
    },
    1414 => {
      :icon_id => 191,
      :title => "Master Battle Fucker",
      :description => "You defeated 52 Battle Fuckers.",
      :priority => 1414,    
    },
    1415 => {
      :icon_id => 191,
      :title => "快楽を極めし者",
      :description => "BF神を破り、快楽を極めし者となった",
      :priority => 1415,    
    },
    1421 => {
      :icon_id => 193,
      :title => "First BF defeat",
      :description => "You received your first defeat in a Battle Fuck.",
      :priority => 1421,    
    },
    1422 => {
      :icon_id => 193,
      :title => "Shameful Loser",
      :description => "You have lost 30 Battle Fucks.",
      :priority => 1422,    
    },
    1423 => {
      :icon_id => 192,
      :title => "The Taste of Defeat",
      :description => "You have lost 50 Battle Fucks; you're addicted to the taste of defeat.",
      :priority => 1423,    
    },
    1501 => {
      :icon_id => 193,
      :title => "Vanilla's Little Shop",
      :description => "The beginning of the item shop: selling herbs.",
      :priority => 1501,    
    },
    1502 => {
      :icon_id => 193,
      :title => "A Nice Shop",
      :description => "A satisfying personal item shop.",
      :priority => 1502,    
    },
    1503 => {
      :icon_id => 192,
      :title => "A Full-fledged Shop",
      :description => "Displaying all the goods Sentora continent has to offer.",
      :priority => 1503,    
    },
    1504 => {
      :icon_id => 192,
      :title => "Vanilla's Megamart",
      :description => "It's become one of the most popular shops in the world.",
      :priority => 1504,    
    },
    1505 => {
      :icon_id => 191,
      :title => "Vanilla the Commerce Queen",
      :description => "Vanilla's Shop now reigns supreme in the world.",
      :priority => 1505,    
    },
    1511 => {
      :icon_id => 193,
      :title => "Papi the Blacksmith",
      :description => "A good first step towards being a master blacksmith.",
      :priority => 1511,    
    },
    1512 => {
      :icon_id => 192,
      :title => "First Class Blacksmith",
      :description => "You even get clients coming from the other side of the world.",
      :priority => 1512,    
    },
    1513 => {
      :icon_id => 192,
      :title => "Top-5 Blacksmith",
      :description => "Papi's skills now rank among the five best blacksmiths in the world.",
      :priority => 1513,    
    },
    1514 => {
      :icon_id => 191,
      :title => "World's Best Blacksmith",
      :description => "Papi has become the best blacksmith in the world.",
      :priority => 1514,    
    },
    # 親方関連
    1520 => {
      :icon_id => 193,
      :title => "スーパー親方",
      :description => "鍛冶レベルが4まで上がった",
      :priority => 1520,
    },
    1521 => {
      :icon_id => 192,
      :title => "ウルトラ親方",
      :description => "鍛冶レベルが8まで上がった",
      :priority => 1521,
    },
    1522 => {
      :icon_id => 191,
      :title => "アルティメット親方",
      :description => "鍛冶レベルが最大まで上がった",
      :priority => 1522,
    },
    1524 => {
      :icon_id => 191,
      :title => "親方を集めし者",
      :description => "世界中に散った親方を全員発見した",
      :priority => 1524,
    },
    # コロシアム
    1601 => {
      :icon_id => 193,
      :title => "Beginner Class Victory",
      :description => "You won the Beginner Class at the Colosseum.",
      :priority => 1601,    
    },
    1602 => {
      :icon_id => 193,
      :title => "Professional Class Victory",
      :description => "You won the Professional Class at the Colosseum.",
      :priority => 1602,    
    },
    1603 => {
      :icon_id => 192,
      :title => "Champion Class Victory",
      :description => "You won the Champion Class at the Colosseum.",
      :priority => 1603,    
    },
    1604 => {
      :icon_id => 191,
      :title => "Unlimited Class Victory",
      :description => "You won the Unlimited Class at the Colosseum.",
      :priority => 1604,    
    },
    1605 => {
      :icon_id => 191,
      :title => "Ultimate Class Victory",
      :description => "You won the Ultimate Class at the Colosseum.",
      :priority => 1605,    
    },
    1606 => {
      :icon_id => 191,
      :title => "Chaos Class Victory",
      :description => "You won the Chaos Class at the Colosseum.",
      :priority => 1606,    
    },
    1611 => {
      :icon_id => 193,
      :title => "Regular Race Cup Victory",
      :description => "You won a Single Race Challenge.",
      :priority => 1611,    
    },
    1612 => {
      :icon_id => 192,
      :title => "Advanced Race Cup Victory",
      :description => "You won a Advanced Race Challenge.",
      :priority => 1612,    
    },
    1613 => {
      :icon_id => 191,
      :title => "Champion Race Cup Victory",
      :description => "You won a Champion Race Challenge.",
      :priority => 1613,    
    },
    1614 => {
      :icon_id => 191,
      :title => "Ultimate Race Cup Victory",
      :description => "You won an Ultimate Race Challenge.",
      :priority => 1614,    
    },
#==============================================================================
    2000 => {
      :icon_id => 193,
      :title => "Freedom",
      :description => "Adventure is a matter of liberty.",
      :priority => 2000,
    },
    2001 => {
      :icon_id => 192,
      :title => "Strike Freedom",
      :description => "Luka, loyal to himself.",
      :priority => 2001,
    },
    2005 => {
      :icon_id => 192,
      :title => "A Desperate Nero",
      :description => "The ordinary traveler seems to have royally screwed up.",
      :priority => 2005,
    },
    2006 => {
      :icon_id => 193,
      :title => "The Murder of Amira",
      :description => "She'll just come back as if nothing even happened.",
      :priority => 2006,
    },
    2007 => {
      :icon_id => 191,
      :title => "Bourgeoisie",
      :description => "You enjoyed the feeling of being rich while staying at an ultra-luxurious inn.",
      :priority => 2007,
    },
    2008 => {
      :icon_id => 193,
      :title => "The Bats of Witch Hunt",
      :description => "You kept your eyes peeled.",
      :priority => 2008,
    },
    2009 => {
      :icon_id => 193,
      :title => "Enlightened Dog Girl",
      :description => "Although she's enlightened, she still loves meaty bones.",
      :priority => 2009,
    },
    2010 => {
      :icon_id => 193,
      :title => "Sheep's World Tour",
      :description => "You spotted the drunken sheep in bars around the world.",
      :priority => 2010,
    },
    2011 => {
      :icon_id => 193,
      :title => "Best Friends",
      :description => "Nuruko and Gnome feel a bond joining them...",
      :priority => 2011,
    },
    2012 => {
      :icon_id => 191,
      :title => "Slot Master",
      :description => "You got 777 in the slot machine.",
      :priority => 2012,
    },
    2013 => {
      :icon_id => 191,
      :title => "In-battle 777",
      :description => "You got 777 while fighting.",
      :priority => 2013,
    },
    2014 => {
      :icon_id => 191,
      :title => "Poker Master",
      :description => "You were dealt a Royal Flush while playing poker.",
      :priority => 2014,
    },
    2015 => {
      :icon_id => 191,
      :title => "In-battle Royal Flush",
      :description => "You were dealt a Royal Flush while fighting.",
      :priority => 2015,
    },
    2016 => {
      :icon_id => 193,
      :title => "Universe in Conflict",
      :description => "You will see the tears of the stars.",
      :priority => 2016,
    },
    2017 => {
      :icon_id => 193,
      :title => "Gravity-defying Imp",
      :description => "We heard rumors about a suicidal imp...",
      :priority => 2017,
    },
    2018 => {
      :icon_id => 193,
      :title => "Chi Pa Pa",
      :description => "The flower on your head goes Chi Pa Pa!",
      :priority => 2018,
    },
    2020 => {
      :icon_id => 193,
      :title => "Find me...",
      :description => "You found Amira hiding in a town.",
      :priority => 2020,
    },
    2021 => {
      :icon_id => 192,
      :title => "The 15th Amira",
      :description => "You found Amira 15 times.",
      :priority => 2021,
    },
    2022 => {
      :icon_id => 192,
      :title => "The 25th Amira",
      :description => "You found Amira 25 times.",
      :priority => 2022,
    },
    2031 => {
      :icon_id => 193,
      :title => "The First Panties",
      :description => "You showed your first panty to Panty Sensei.",
      :priority => 2031,
    },
    2032 => {
      :icon_id => 192,
      :title => "Panty Collector",
      :description => "You showed 50 panties to Panty Sensei.",
      :priority => 2032,
    },
    2033 => {
      :icon_id => 192,
      :title => "Panty Master",
      :description => "You showed 120 panties to Panty Sensei.",
      :priority => 2033,
    },
    2034 => {
      :icon_id => 192,
      :title => "Panties King",
      :description => "You showed 200 panties to Panty Sensei.",
      :priority => 2034,
    },
    2035 => {
      :icon_id => 191,
      :title => "Panties God",
      :description => "Thank you... That's all we can say.",
      :priority => 2035,
    },
    2039 => {
      :icon_id => 191,
      :title => "The Death of Panty Sensei",
      :description => "All the perverts of the world wept over his death.",
      :priority => 2039,
    },
    2101 => {
      :icon_id => 193,
      :title => "Green Post",
      :description => "A new Queen Alraune was born.",
      :priority => 2101,
    },
    2102 => {
      :icon_id => 193,
      :title => "El's Social Studies",
      :description => "She may be one step closer to being the next Queen Mermaid.",
      :priority => 2102,
    },
    2103 => {
      :icon_id => 193,
      :title => "Queen Insect",
      :description => "The next Queen Insect has been joyously decided.",
      :priority => 2103,
    },
    2104 => {
      :icon_id => 193,
      :title => "Your True Name Is Alucart",
      :description => "Celebrating the success of the vampire pub, Vanilla was given a real name.",
      :priority => 2104,
    },
    2105 => {
      :icon_id => 193,
      :title => "Magic King's Determination",
      :description => "King Grangold overcame his hesitation.",
      :priority => 2105,
    },
    2106 => {
      :icon_id => 193,
      :title => "Beautiful World",
      :description => "The two seraphs experienced the splendor of nature.",
      :priority => 2106,
    },
    2107 => {
      :icon_id => 193,
      :title => "Spiritualized Lucia",
      :description => "Lucia developed a secret technique to elementalize the human body.",
      :priority => 2107,
    },
    2108 => {
      :icon_id => 193,
      :title => "Gloria Pirates Defeated",
      :description => "You defeated the Gloria Pirate battle fuckers.",
      :priority => 2108,
    },
    2109 => {
      :icon_id => 193,
      :title => "Mysterious Medal King",
      :description => "You found the first Medal King.",
      :priority => 2109,
    },
    2110 => {
      :icon_id => 193,
      :title => "Polar Bear Helper",
      :description => "You brought a lost Polar Bear Girl back home.",
      :priority => 2110,
    },
    2111 => {
      :icon_id => 193,
      :title => "Canaan Sisters Discount",
      :description => "You haggled the three Canaan Sisters and got a bonus.",
      :priority => 2111,
    },
    2112 => {
      :icon_id => 193,
      :title => "Delete Yourself",
      :description => "You were wiped out by the Reaper.",
      :priority => 2112,
    },
    2113 => {
      :icon_id => 193,
      :title => "You Finally Understand?",
      :description => "Eden learned the error of her past mistakes.",
      :priority => 2113,
    },
    2114 => {
      :icon_id => 192,
      :title => "Succubi and Fists",
      :description => "Alma Elma has acknowledged your power.",
      :priority => 2114,
    },
    2115 => {
      :icon_id => 192,
      :title => "Beyond Race Boundaries",
      :description => "Changing to different races has now became possible.",
      :priority => 2115,
    },
    2116 => {
      :icon_id => 193,
      :title => "Whoa! This is!",
      :description => "You read a naughty book.",
      :priority => 2116,
    },
    2117 => {
      :icon_id => 193,
      :title => "Ant's Farewell",
      :description => "Kyona confronted the sins of her past.",
      :priority => 2117,
    },
    2118 => {
      :icon_id => 193,
      :title => "The Rabbit's Arrow",
      :description => "The Rabbit Girl learned the secret skills of the elves.",
      :priority => 2118,
    },
    2119 => {
      :icon_id => 193,
      :title => "Ryugu Dance ☆",
      :description => "Saki has mastered the dance of the sea.",
      :priority => 2119,
    },
    2120 => {
      :icon_id => 191,
      :title => "The Land of Night and the Heroes of the Seven Worlds",
      :description => "You have defeated the Queen of Dreams and resolved a major incident.",
      :priority => 2120,
    },
    2121 => {
      :icon_id => 191,
      :title => "Nightmares of the Seven Worlds",
      :description => "You have made all the members of Est's alliance into your allies.",
      :priority => 2121,
    },
    2122 => {
      :icon_id => 192,
      :title => "Plague-Dispersing Amabie-sama",
      :description => "Amabie has saved everyone.",
      :priority => 2122,
    },
    2123 => {
      :icon_id => 192,
      :title => "Cassandra Strikes Back",
      :description => "You have defeated Cassandra at her strongest.",
      :priority => 2123,
    },
    2124 => {
      :icon_id => 191,
      :title => "Promestein's Gate",
      :description => "You have resolved the time loop.",
      :priority => 2124,
    },
    2125 => {
      :icon_id => 191,
      :title => "Jubilant Festival",
      :description => "You enjoyed the Yamatai night festival.",
      :priority => 2125,
    },
    2126 => {
      :icon_id => 193,
      :title => "Borrowed Child of the Earth",
      :description => "You have fulfilled Tamamo's request.",
      :priority => 2126,
    },
    2127 => {
      :icon_id => 193,
      :title => "Rose of Heaven",
      :description => "You have fulfilled Kanon's request.",
      :priority => 2127,
    },
    2128 => {
      :icon_id => 193,
      :title => "The Most Delicious Thing in Heaven",
      :description => "You have fulfilled Hiruko's request.",
      :priority => 2128,
    },
    2129 => {
      :icon_id => 193,
      :title => "A Present for Lady Kanade",
      :description => "You brought Kanade a present.",
      :priority => 2129,
    },
    2130 => {
      :icon_id => 193,
      :title => "Be Strong, Monster Lord",
      :description => "You have been entrusted with an item from Saja.",
      :priority => 2130,
    },
    2131 => {
      :icon_id => 193,
      :title => "Luka, Who Stands Alongside the Monster Lord",
      :description => "You have been entrusted with an item from Minagi.",
      :priority => 2131,
    },
    2132 => {
      :icon_id => 193,
      :title => "A Lecher with a Quiet Exterior",
      :description => "You have fulfilled Raphaela's request.",
      :priority => 2132,
    },
    2133 => {
      :icon_id => 193,
      :title => "Recovering Sacred Weapons",
      :description => "You have fulfilled Gabriela's request.",
      :priority => 2133,
    },
    2134 => {
      :icon_id => 193,
      :title => "Mechanical Weapon Mania",
      :description => "You have fulfilled Uriela's request.",
      :priority => 2134,
    },
    2135 => {
      :icon_id => 193,
      :title => "Sariela's Smile",
      :description => "You gave Sariela some ancient sushi to eat.",
      :priority => 2135,
    },
    2136 => {
      :icon_id => 193,
      :title => "Weird Mascot Doll",
      :description => "You fulfilled the twin sister angels' request.",
      :priority => 2136,
    },
    2137 => {
      :icon_id => 192,
      :title => "Together, We Are King of Sabasa!",
      :description => "You have combined the soul fragments and brought the King of Sabasa into your party.",
      :priority => 2137,
    },
    2138 => {
      :icon_id => 191,
      :title => "Ultimate Living Weapon of the Dark Goddess",
      :description => "You have made Giganto Weapon into your companion.",
      :priority => 2138,
    },
    2139 => {
      :icon_id => 191,
      :title => "Ultimate Living Weapon of the Goddess",
      :description => "You have made Nephilim Weapon into your companion.",
      :priority => 2139,
    },
    2140 => {
      :icon_id => 193,
      :title => "Gimme me an Elixir!",
      :description => "You beat up the Magic Pot hiding in the Elf Princess' Mansion.",
      :priority => 2140,
    },
    2141 => {
      :icon_id => 193,
      :title => "家族消沈",
      :description => "ルカ一家の社会性の無さが示された",
      :priority => 2141,
    },
    2142 => {
      :icon_id => 193,
      :title => "World's Tallest Mountain Conquered",
      :description => "Rami may have been able to conquer Mt. Horai, the tallest mountain in the world, but she still can't fly.",
      :priority => 2142,
    },
    2143 => {
      :icon_id => 193,
      :title => "Dashing Through Space",
      :description => "Although Rami couldn't fly, she performed the world's first space walk.",
      :priority => 2143,
    },
    2144 => {
      :icon_id => 193,
      :title => "勇者の挫折1",
      :description => "1と数字がついている時点で、二度目があるのは明らかだ",
      :priority => 2145,
    },
    2145 => {
      :icon_id => 193,
      :title => "勇者の挫折2",
      :description => "二度の挫折の後、北の勇者は己を見つめ直した",
      :priority => 2146,
    },
    2146 => {
      :icon_id => 193,
      :title => "勇者の挫折3",
      :description => "またも自身の弱さを思い知ったが、北の勇者は晴れやかだった",
      :priority => 2147,
    },
    2147 => {
      :icon_id => 193,
      :title => "北の勇者、旅立ち",
      :description => "北の勇者は世界を救う冒険に旅立った",
      :priority => 2148,
    },
    2148 => {
      :icon_id => 193,
      :title => "ゆうべはおたのしみでしたね",
      :description => "トランプをしたり枕投げをしたり、その他色々と楽しんだ",
      :priority => 2149,
    },
    2149 => {
      :icon_id => 193,
      :title => "Galaxy Superhero",
      :description => "You have made Cosmic Woman into your companion.",
      :priority => 2144,
    },
    2150 => {
      :icon_id => 191,
      :title => "The One Who Broke All Seals",
      :description => "You removed all of the seals in Mithra Sealed Castle.",
      :priority => 2150,
    },
    2151 => {
      :icon_id => 191,
      :title => "Music Completion",
      :description => "You collected all of the CDs.",
      :priority => 2151,
    },
    2152 => {
      :icon_id => 191,
      :title => "宝剣を携えし者",
      :description => "妖精の島で二振りの宝剣を受け取った",
      :priority => 2152,
    },
    2153 => {
      :icon_id => 191,
      :title => "異種間転種を網羅せし者",
      :description => "全ての異種間転種が可能になった",
      :priority => 2153,
    },
    2154 => {
      :icon_id => 193,
      :title => "Close Encounters of the Third Kind",
      :description => "You encountered a mysterious intelligent lifeform on the moon's surface.",
      :priority => 2154,
    },
    2155 => {
      :icon_id => 191,
      :title => "Crossover Event",
      :description => "Heroes from another world have gathered togeher.",
      :priority => 2155,
    },
    2156 => {
      :icon_id => 191,
      :title => "Apollo's Remembrance",
      :description => "The flag of a forgotten nation still remains on the moon.",
      :priority => 2156,
    },

#==============================================================================
    3001 => {
      :icon_id => 191,
      :title => "ANGELKILLKILL",
      :description => "You defeated the Armored Berserker.",
      :priority => 3001,
    },
    3002 => {
      :icon_id => 192,
      :title => "Seventh Heaven",
      :description => "You defeated Nanabi.",
      :priority => 3002,
    },
    3003 => {
      :icon_id => 192,
      :title => "I Hate Riddles",
      :description => "You defeated Sphinx.",
      :priority => 3003,
    },
    3004 => {
      :icon_id => 192,
      :title => "Monster Lord's Defeat?",
      :description => "You defeated Hades Alice.",
      :priority => 3004,
    },
    3005 => {
      :icon_id => 191,
      :title => "One Who Conquered Death",
      :description => "You defeated Reaper.",
      :priority => 3005,
    },
    3006 => {
      :icon_id => 191,
      :title => "Champion of the Ocean",
      :description => "You defeated Leviathan.",
      :priority => 3006,
    },
    3007 => {
      :icon_id => 191,
      :title => "You Who Stood in the Flames and Asked Me",
      :description => "You defeated Yamata no Orochi.",
      :priority => 3007,
    },
    3008 => {
      :icon_id => 191,
      :title => "The Moon is a Harsh Mistress",
      :description => "You defeated Tamamo.",
      :priority => 3008,
    },
    3009 => {
      :icon_id => 191,
      :title => "In Heinrich's Stead",
      :description => "You defeated Black Alice.",
      :priority => 3009,
    },
    3070 => {
      :icon_id => 191,
      :title => "未踏の英雄",
      :description => "You reached the true ending without entering the Labyrinth of Chaos.",
      :priority => 3070,
    },
#    3081 => {
#      :icon_id => 193,
#      :title => "Trial Challenger",
#      :description => "Cleared Trial of Chaos Level 1.",
#      :priority => 3081,
#    },
#    3082 => {
#      :icon_id => 192,
#      :title => "Trial Expert",
#      :description => "Cleared Trial of Chaos Level 2.",
#      :priority => 3082,
#    },
#    3083 => {
#      :icon_id => 192,
#     :title => "Trial Master",
#      :description => "Cleared Trial of Chaos Level 3.",
#      :priority => 3083,
#    },
#    3084 => {
#      :icon_id => 191,
#      :title => "Trial God",
#      :description => "Cleared Trial of Chaos Level 4.",
#      :priority => 3084,
#    },
#    3085 => {
#      :icon_id => 191,
#      :title => "Trial Chaos",
#      :description => "Cleared Trial of Chaos Level 5.",
#      :priority => 3085,
#    },
    3100 => {
      :icon_id => 193,
      :title => "Labyrinth Challenger",
      :description => "You reached the 10th level of the Labyrinth of Chaos.",
      :priority => 3100,
    },
    3101 => {
      :icon_id => 192,
      :title => "Labyrinth Expert",
      :description => "You reached the 50th level of the Labyrinth of Chaos.",
      :priority => 3101,
    },
    3102 => {
      :icon_id => 192,
      :title => "Labyrinth Master",
      :description => "You reached the 100th level of the Labyrinth of Chaos.",
      :priority => 3102,
    },
    3103 => {
      :icon_id => 191,
      :title => "Labyrinth God",
      :description => "You reached the 200th level of the Labyrinth of Chaos.",
      :priority => 3103,
    },
    3104 => {
      :icon_id => 191,
      :title => "Labyrinth Chaos",
      :description => "You reached the 300th level of the Labyrinth of Chaos.",
      :priority => 3104,
    },
    3110 => {
      :icon_id => 193,
      :title => "Carnage Beginner",
      :description => "You reached the 20th floor of the Carnage Labyrinth of Chaos.",
      :priority => 3110,
    },
    3111 => {
      :icon_id => 192,
      :title => "True Carnage",
      :description => "You reached the 50th floor of the Carnage Labyrinth of Chaos.",
      :priority => 3111,
    },
    3112 => {
      :icon_id => 191,
      :title => "The Heart of Carnage",
      :description => "You reached the 100th floor of the Carnage Labyrinth of Chaos.",
      :priority => 3112,
    },
    4001=> {
      :icon_id => 193,
      :title => "Reaper is Smiling",
      :description => "You inflicted over a million damage in the Reaper Challenge.",
      :priority => 4001,
    },
    4002=> {
      :icon_id => 192,
      :title => "Reaper is Amazed",
      :description => "You inflicted over a hundred million damage in the Reaper Challenge.",
      :priority => 4002,
    },
    4003=> {
      :icon_id => 191,
      :title => "Reaper's Reaper",
      :description => "You inflicted over a trillion damage in the Reaper Challenge.",
      :priority => 4003,
    },

  }
end

